replace_with = {'ṭ': 't',
                'ᵈ': 'd',
                'ɡ': 'g',
                'ᶢ': 'g',
                'ḿ': 'm',
                'ᵐ': 'm',
                'ᶬ': 'ɱ',
                'ṅ': 'n',
                'ṇ': 'n',
                'ǹ': 'n',
                'ⁿ': 'n',
                'ñ': 'ɲ',
                'ᵑ': 'ŋ',
                'ŕ': 'r',
                'ṛ': 'r',
                'ḥ': 'h',
                'ĺ': 'l',
                'ḹ': 'l',
                }

letters = {'p': {'LB', 'PL'},
           'b': {'LB', 'PL', 'VO'},
           't': {'AL', 'PL'},
           'd': {'AL', 'PL', 'VO'},
           'ʈ': {'RE', 'PL'},
           'ɖ': {'RE', 'PL', 'VO'},
           'c': {'PA', 'PL'},
           'ɟ': {'PA', 'PL', 'VO'},
           'k': {'VE', 'PL'},
           'g': {'VE', 'PL', 'VO'},
           'q': {'UV', 'PL'},
           'ɢ': {'UV', 'PL', 'VO'},
           'ʡ': {'PH', 'PL'},
           'ʔ': {'GL', 'PL'},

           'm': {'LB', 'NA', 'VO'},
           'ɱ': {'LD', 'NA', 'VO'},
           'n': {'AL', 'NA', 'VO'},
           'ɳ': {'RE', 'NA', 'VO'},
           'ɲ': {'PA', 'NA', 'VO'},
           'ŋ': {'VE', 'NA', 'VO'},
           'ɴ': {'UV', 'NA', 'VO'},

           'ʙ': {'LB', 'VI', 'VO'},
           'r': {'AL', 'VI', 'VO'},
           'ʀ': {'UV', 'VI', 'VO'},
           'ʜ': {'PH', 'VI'},
           'ʢ': {'PH', 'VI', 'VO'},

           'ⱱ': {'LD', 'TA', 'VO'},
           'ɾ': {'AL', 'TA', 'VO'},
           'ɽ': {'RE', 'TA', 'VO'},

           'ɸ': {'LB', 'NS'},
           'β': {'LB', 'NS', 'VO'},
           'f': {'LD', 'NS'},
           'v': {'LD', 'NS', 'VO'},
           'θ': {'DE', 'NS'},
           'ð': {'DE', 'NS', 'VO'},
           's': {'AL', 'SS'},
           'z': {'AL', 'SS', 'VO'},
           'ʃ': {'PO', 'SS'},
           'ʒ': {'PO', 'SS', 'VO'},
           'ʂ': {'RE', 'SS'},
           'ʐ': {'RE', 'SS', 'VO'},
           'ç': {'PA', 'NS'},
           'ʝ': {'PA', 'NS', 'VO'},
           'x': {'VE', 'NS'},
           'ɣ': {'VE', 'NS', 'VO'},
           'χ': {'UV', 'NS'},
           'ʁ': {'UV', 'NS', 'VO'},
           'ħ': {'PH', 'NS'},
           'ʕ': {'PH', 'NS', 'VO'},
           'h': {'GL', 'NS'},
           'ɦ': {'GL', 'NS', 'VO'},
           'ɬ': {'AL', 'NS', 'LA'},
           'ɮ': {'AL', 'NS', 'LA', 'VO'},

           'ʋ': {'LD', 'SV', 'VO'},
           'ɹ': {'AL', 'SV', 'VO'},
           'ɻ': {'RE', 'SV', 'VO'},
           'j': {'PA', 'SV', 'VO'},
           'ɰ': {'VE', 'SV', 'VO'},

           'l': {'AL', 'SV', 'LA', 'VO'},
           'ɭ': {'RE', 'SV', 'LA', 'VO'},
           'ʎ': {'PA', 'SV', 'LA', 'VO'},
           'ʟ': {'VE', 'SV', 'LA', 'VO'},

           'ʘ': {'LB', 'PL', 'EJ', 'IN'},
           'ǀ': {'DE', 'PL', 'EJ', 'IN'},
           'ǃ': {'AL', 'PL', 'EJ', 'IN'},
           '‼': {'RE', 'PL', 'EJ', 'IN'},
           'ǂ': {'PA', 'PL', 'EJ', 'IN'},
           'ʞ': {'VE', 'PL', 'EJ', 'IN'},
           'ǁ': {'PL', 'LA', 'EJ', 'IN'},

           'ɓ': {'LB', 'PL', 'VO', 'IN'},
           'ɗ': {'AL', 'PL', 'VO', 'IN'},
           'ᶑ': {'RE', 'PL', 'VO', 'IN'},
           'ʄ': {'PA', 'PL', 'VO', 'IN'},
           'ɠ': {'VE', 'PL', 'VO', 'IN'},
           'ʛ': {'UV', 'PL', 'VO', 'IN'},

           'ʍ': {'LZ', 'VZ', 'SV'},
           'w': {'LZ', 'VZ', 'SV', 'VO'},
           'ɥ': {'LZ', 'PZ', 'SV', 'VO'},
           'ɫ': {'AL', 'VZ', 'SV', 'LA', 'VO'},
           'ɺ': {'AL', 'TA', 'LA', 'VO'},
           'ɕ': {'AL', 'PA', 'SS'},
           'ʑ': {'AL', 'PA', 'SS', 'VO'},
           'ȵ': {'AL', 'PA', 'VO', 'NA'},
           'ɧ': {'PO', 'VE', 'SS'},

           'i': {'PA', 'CL', 'VO'},
           'ĩ': {'PA', 'CL', 'VO', 'NA'},
           'ī': {'PA', 'CL', 'VO', 'replace_with': 'i'},
           'î': {'PA', 'CL', 'VO', 'replace_with': 'i'},
           'í': {'PA', 'CL', 'VO', 'replace_with': 'i'},
           'ì': {'PA', 'CL', 'VO', 'replace_with': 'i'},
           'ḭ': {'PA', 'CL', 'VO', 'replace_with': 'i'},
           'ǐ': {'PA', 'CL', 'VO', 'replace_with': 'i'},
           'y': {'LB': 6, 'PA': 6, 'CL', 'VO'},
           'ỹ': {'LB': 6, 'PA': 6, 'CL', 'VO', 'NA'},
           'ý': {'LB': 6, 'PA': 6, 'CL', 'VO', 'replace_with': 'y'},
           'ẏ': {'LB': 6, 'PA': 6, 'CL', 'VO', 'replace_with': 'y'},
           'ɨ': {'PA': 6, 'VE': 6, 'CL', 'VO'},
           'ʉ': {'LB': 6, 'PA': 3, 'VE': 3, 'CL', 'VO'},
           'ɯ': {'VE', 'CL', 'VO'},
           'u': {'LB': 6, 'VE': 6, 'CL', 'VO'},
           'ũ': {'LB': 6, 'VE': 6, 'CL', 'VO', 'NA'},
           'ù': {'LB': 6, 'VE': 6, 'CL', 'VO', 'replace_with': 'u'},
           'ū': {'LB': 6, 'VE': 6, 'CL', 'VO', 'replace_with': 'u'},
           'ú': {'LB': 6, 'VE': 6, 'CL', 'VO', 'replace_with': 'u'},
           'û': {'LB': 6, 'VE': 6, 'CL', 'VO', 'replace_with': 'u'},
           'ǔ': {'LB': 6, 'VE': 6, 'CL', 'VO', 'replace_with': 'u'},
           'ṵ': {'LB': 6, 'VE': 6, 'CL', 'VO', 'replace_with': 'u'},
           'ṳ': {'LB': 6, 'VE': 6, 'CL', 'VO', 'replace_with': 'u'},
           'ɪ': {'PA': 8, 'VE': 4, 'CL': 10, 'OP': 2, 'VO'},
           'ʏ': {'LB': 6, 'PA': 4, 'VE': 2, 'CL': 10, 'OP': 2, 'VO'},
           'ʊ': {'LB': 6, 'PA': 2, 'VE': 4, 'CL': 10, 'OP': 2, 'VO'},
           'e': {'PA', 'CL': 8, 'OP': 4, 'VO'},
           'ẽ': {'PA', 'CL': 8, 'OP': 4, 'VO', 'NA'},
           'é': {'PA', 'CL': 8, 'OP': 4, 'VO', 'replace_with': 'e'},
           'è': {'PA', 'CL': 8, 'OP': 4, 'VO', 'replace_with': 'e'},
           'ê': {'PA', 'CL': 8, 'OP': 4, 'VO', 'replace_with': 'e'},
           'ĕ': {'PA', 'CL': 8, 'OP': 4, 'VO', 'replace_with': 'e'},
           'ě': {'PA', 'CL': 8, 'OP': 4, 'VO', 'replace_with': 'e'},
           'ḛ': {'PA', 'CL': 8, 'OP': 4, 'VO', 'replace_with': 'e'},
           'ø': {'LB': 6, 'PA': 6, 'CL': 8, 'OP': 4, 'VO'},
           'ɘ': {'PA': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO'},
           'ɵ': {'LB': 6, 'PA': 3, 'VE': 3, 'CL': 8, 'OP': 4, 'VO'},
           'ɤ': {'VE', 'CL': 8, 'OP': 4, 'VO'},
           'o': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO'},
           'õ': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO', 'NA'},
           'ó': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO', 'replace_with': 'o'},
           'ò': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO', 'replace_with': 'o'},
           'ô': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO', 'replace_with': 'o'},
           'ō': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO', 'replace_with': 'o'},
           'ə': {'PA': 6, 'VE': 6, 'CL': 6, 'OP': 6, 'VO'},
           'ɛ': {'PA', 'CL': 4, 'OP': 8, 'VO'},
           'œ': {'LB': 6, 'PA': 6, 'CL': 4, 'OP': 8, 'VO'},
           'ɜ': {'PA': 6, 'VE': 6, 'CL': 4, 'OP': 8, 'VO'},
           'ɞ': {'LB': 6, 'PA': 3, 'VE': 3, 'CL': 4, 'OP': 8, 'VO'},
           'ʌ': {'VE', 'CL': 4, 'OP': 8, 'VO'},
           'ɔ': {'LB': 6, 'VE': 6, 'CL': 4, 'OP': 8, 'VO'},
           'æ': {'PA', 'CL': 2, 'OP': 10, 'VO'},
           'ǣ': {'PA', 'CL': 2, 'OP': 10, 'VO', 'replace_with': 'æ'},
           'ɐ': {'PA': 6, 'VE': 6, 'CL': 2, 'OP': 10, 'VO'},
           'a': {'PA', 'OP', 'VO'},
           'ã': {'PA', 'OP', 'VO', 'NA'},
           'á': {'PA', 'OP', 'VO', 'replace_with': 'a'},
           'â': {'PA', 'OP', 'VO', 'replace_with': 'a'},
           'ā': {'PA', 'OP', 'VO', 'replace_with': 'a'},
           'à': {'PA', 'OP', 'VO', 'replace_with': 'a'},
           'ǎ': {'PA', 'OP', 'VO', 'replace_with': 'a'},
           'ạ': {'PA', 'OP', 'VO', 'replace_with': 'a'},
           'ɶ': {'LB': 6, 'PA': 6, 'OP', 'VO'},
           'ä': {'PA': 6, 'VE': 6, 'OP', 'VO'},
           'ɑ': {'VE', 'OP', 'VO'},
           'ɒ': {'LB': 6, 'VE': 6, 'OP', 'VO'},
           'ɚ': {'AL': 6, 'PA': 3, 'VE': 3, 'CL': 6, 'OP': 6, 'VO'},
           'ɝ': {'AL': 6, 'PA': 3, 'VE': 3, 'CL': 4, 'OP': 8, 'VO'}
           }

ignore_set = {'.', 'ˈ', 'ˌ', 'ː', 'ˑ', '*', '´', '′', '˘', '˧', '˩', '˨', '˦', '˥', 'ꜜ', '1',
              '2', '²', '³', '⁽', '⁾', '/', '(', ')', '⟨', '⟩', 'ˣ', '‿', ' ',
              u'\u0300', u'\u0301', u'\u0302', u'\u0304', u'\u030c', u'\u031a', u'\u0320',
              u'\u0324', u'\u0329', u'\u032f', u'\u0330', u'\u033a', u'\u033b', u'\u035C',
              u'\u0361', u'\u1dc4', u'\u1dc5', u'\u1dc8'}

modifiers = {'ᵝ': {'action': 'add', 'args': ['LB']},
             '˞': {'action': 'add', 'args': ['AL']},
             'ʴ': {'action': 'add', 'args': ['AL'], 'replace_with': '˞'},
             'ʲ': {'action': 'add', 'args': ['PA']},
             'ˠ': {'action': 'add', 'args': ['VE']},
             'ʷ': {'action': 'add', 'args': ['LB', 'VE']},
             'ˁ': {'action': 'add', 'args': ['PH']},
             'ˀ': {'action': 'add', 'args': ['GL']},
             'ˡ': {'action': 'add', 'args': ['LA']},
             'ʰ': {'action': 'add', 'args': ['AS']},
             'ʱ': {'action': 'add', 'args': ['AS', 'VO']},
             'ʼ': {'action': 'add', 'args': ['EJ']},
             u'\u0303': {'action': 'add', 'args': ['NA']},
             u'\u030a': {'action': 'devoice', 'args': []},
             u'\u0322': {'action': 'make', 'args': ['places', 'RE']},
             u'\u0325': {'action': 'devoice', 'args': []},
             u'\u032c': {'action': 'add', 'args': ['VO']},
             u'\u031f': {'action': 'advance', 'args': []},
             u'\u031e': {'action': 'lower', 'args': []},
             u'\u031d': {'action': 'upper', 'args': []},
             u'\u032a': {'action': 'dentalize', 'args': []},
             u'\u0339': {'action': 'half_labialize', 'args': []},
             u'\u02be': {'action': 'half_labialize', 'args': []},
             u'\u0348': {'action': 'intensify', 'args': []},
             'ṃ': {'action': 'add', 'args': ['NA'], 'replace_with': u'\u0303'}
             }

coronals = {'DE', 'AL', 'PO', 'RE'}
places = {'LB', 'LD', 'LL', 'DE', 'AL', 'PO', 'RE', 'PA', 'NE', 'VE', 'UV', 'PH', 'GL'}
secondaries = {'LZ', 'RZ', 'PZ', 'VZ', 'HZ', 'NZ'}
manners = {'NA', 'PL', 'NF', 'SF', 'NS', 'SS', 'VI', 'TA', 'CL', 'NC', 'MC', 'MI', 'MO', 'NO', 'OP'}
lateralization = {'LA'}
voiceness = {'VO'}
airflows = {'AS', 'EJ', 'IN'}
features = {'places': places,
            'secondaries': secondaries,
            'manners': manners,
            'lateralization': lateralization,
            'voiceness': voiceness,
            'airflows': airflows}

feature_names = {'LB': 'Labial', 'LD': 'Labiodental', 'LL': 'Labiolingual', 'DE': 'Dental',
                 'AL': 'Alveolar', 'PO': 'Postalveolar', 'RE': 'Retroflex', 'PA': 'Palatal',
                 'NE': 'Neutral', 'VE': 'Velar', 'UV': 'Uvular', 'PH': 'Pharyngeal', 'GL': 'Glotal',
                 'LZ': 'Labialized', 'RZ': 'Rhoticized', 'PZ': 'Palatalized', 'VZ': 'Velarized', 'HZ': 'Pharyngealized',
                 'NZ': 'Nasalized', 'NA': 'Nasal', 'PL': 'Plosive', 'NF': 'Nonsibilant affricate', 'SF': 'Sibilant affricate',
                 'NS': 'Nonsibilant fricative', 'SS': 'Sibilant fricative', 'VI': 'Vibrant', 'TA': 'Tap',
                 'SV': 'Approximant', 'CL': 'Closed', 'NC': 'Near-closed', 'MC': 'Mid-closed', 'MI': 'Mid',
                 'MO': 'Mid-open', 'NO': 'Near-open', 'OP': 'Opened', 'LA': 'Lateral',
                 'VO': 'Voiced', 'AS': 'Aspirated', 'EJ': 'Ejective', 'IN': 'Ingressive'}
