replace_with = {'ṭ': 't',
                'ᵈ': 'd',
                'ɡ': 'g',
                'ᶢ': 'g',
                'ḿ': 'm',
                'ᵐ': 'm',
                'ᶬ': 'ɱ',
                'ṅ': 'n',
                'ṇ': 'n',
                'ǹ': 'n',
                'ⁿ': 'n',
                'ñ': 'ɲ',
                'ᵑ': 'ŋ',
                'ŕ': 'r',
                'ṛ': 'r',
                'ḥ': 'h',
                'ĺ': 'l',
                'ḹ': 'l',

                'ī': 'i',
                'î': 'i',
                'í': 'i',
                'ì': 'i',
                'ḭ': 'i',
                'ǐ': 'i',
                'ý': 'y',
                'ẏ': 'y',
                'ù': 'u',
                'ū': 'u',
                'ú': 'u',
                'û': 'u',
                'ǔ': 'u',
                'ṵ': 'u',
                'ṳ': 'u',
                'é': 'e',
                'è': 'e',
                'ê': 'e',
                'ĕ': 'e',
                'ě': 'e',
                'ḛ': 'e',
                'ó': 'o',
                'ò': 'o',
                'ô': 'o',
                'ō': 'o',
                'ǣ': 'æ',
                'á': 'a',
                'â': 'a',
                'ā': 'a',
                'à': 'a',
                'ǎ': 'a',
                'ạ': 'a',

                'ʴ': '˞',
                'ṃ': u'\u0303'
                }

letters = {'p': {'LB', 'PL'},
           'b': {'LB', 'PL', 'VO'},
           't': {'AL', 'PL'},
           'd': {'AL', 'PL', 'VO'},
           'ʈ': {'RE', 'PL'},
           'ɖ': {'RE', 'PL', 'VO'},
           'c': {'PA', 'PL'},
           'ɟ': {'PA', 'PL', 'VO'},
           'k': {'VE', 'PL'},
           'g': {'VE', 'PL', 'VO'},
           'q': {'UV', 'PL'},
           'ɢ': {'UV', 'PL', 'VO'},
           'ʡ': {'PH', 'PL'},
           'ʔ': {'GL', 'PL'},

           'm': {'LB', 'NA', 'VO'},
           'ɱ': {'LD', 'NA', 'VO'},
           'n': {'AL', 'NA', 'VO'},
           'ɳ': {'RE', 'NA', 'VO'},
           'ɲ': {'PA', 'NA', 'VO'},
           'ŋ': {'VE', 'NA', 'VO'},
           'ɴ': {'UV', 'NA', 'VO'},

           'ʙ': {'LB', 'VI', 'VO'},
           'r': {'AL', 'VI', 'VO'},
           'ʀ': {'UV', 'VI', 'VO'},
           'ʜ': {'PH', 'VI'},
           'ʢ': {'PH', 'VI', 'VO'},

           'ⱱ': {'LD', 'TA', 'VO'},
           'ɾ': {'AL', 'TA', 'VO'},
           'ɽ': {'RE', 'TA', 'VO'},

           'ɸ': {'LB', 'NS'},
           'β': {'LB', 'NS', 'VO'},
           'f': {'LD', 'NS'},
           'v': {'LD', 'NS', 'VO'},
           'θ': {'DE', 'NS'},
           'ð': {'DE', 'NS', 'VO'},
           's': {'AL', 'SS'},
           'z': {'AL', 'SS', 'VO'},
           'ʃ': {'PO', 'SS'},
           'ʒ': {'PO', 'SS', 'VO'},
           'ʂ': {'RE', 'SS'},
           'ʐ': {'RE', 'SS', 'VO'},
           'ç': {'PA', 'NS'},
           'ʝ': {'PA', 'NS', 'VO'},
           'x': {'VE', 'NS'},
           'ɣ': {'VE', 'NS', 'VO'},
           'χ': {'UV', 'NS'},
           'ʁ': {'UV', 'NS', 'VO'},
           'ħ': {'PH', 'NS'},
           'ʕ': {'PH', 'NS', 'VO'},
           'h': {'GL', 'NS'},
           'ɦ': {'GL', 'NS', 'VO'},
           'ɬ': {'AL', 'NS', 'LA'},
           'ɮ': {'AL', 'NS', 'LA', 'VO'},

           'ʋ': {'LD', 'SV', 'VO'},
           'ɹ': {'AL', 'SV', 'VO'},
           'ɻ': {'RE', 'SV', 'VO'},
           'j': {'PA', 'SV', 'VO'},
           'ɰ': {'VE', 'SV', 'VO'},

           'l': {'AL', 'SV', 'LA', 'VO'},
           'ɭ': {'RE', 'SV', 'LA', 'VO'},
           'ʎ': {'PA', 'SV', 'LA', 'VO'},
           'ʟ': {'VE', 'SV', 'LA', 'VO'},

           'ʘ': {'LB', 'PL', 'EJ', 'IN'},
           'ǀ': {'DE', 'PL', 'EJ', 'IN'},
           'ǃ': {'AL', 'PL', 'EJ', 'IN'},
           '‼': {'RE', 'PL', 'EJ', 'IN'},
           'ǂ': {'PA', 'PL', 'EJ', 'IN'},
           'ʞ': {'VE', 'PL', 'EJ', 'IN'},
           'ǁ': {'PL', 'LA', 'EJ', 'IN'},

           'ɓ': {'LB', 'PL', 'VO', 'IN'},
           'ɗ': {'AL', 'PL', 'VO', 'IN'},
           'ᶑ': {'RE', 'PL', 'VO', 'IN'},
           'ʄ': {'PA', 'PL', 'VO', 'IN'},
           'ɠ': {'VE', 'PL', 'VO', 'IN'},
           'ʛ': {'UV', 'PL', 'VO', 'IN'},

           'ʍ': {'LZ', 'VZ', 'SV'},
           'w': {'LZ', 'VZ', 'SV', 'VO'},
           'ɥ': {'LZ', 'PZ', 'SV', 'VO'},
           'ɫ': {'AL', 'VZ', 'SV', 'LA', 'VO'},
           'ɺ': {'AL', 'TA', 'LA', 'VO'},
           'ɕ': {'AL', 'PA', 'SS'},
           'ʑ': {'AL', 'PA', 'SS', 'VO'},
           'ȵ': {'AL', 'PA', 'VO', 'NA'},
           'ɧ': {'PO', 'VE', 'SS'},

           'i': {'PA', 'CL', 'VO'},
           'ĩ': {'PA', 'CL', 'VO', 'NZ'},
           'y': {'LZ', 'PA', 'CL', 'VO'},
           'ỹ': {'LZ', 'PA', 'CL', 'VO', 'NZ'},
           'ɨ': {'NE', 'CL', 'VO'},
           'ʉ': {'LZ', 'NE', 'CL', 'VO'},
           'ɯ': {'VE', 'CL', 'VO'},
           'u': {'LZ', 'VE', 'CL', 'VO'},
           'ũ': {'LZ', 'VE', 'CL', 'VO', 'NZ'},
           'ɪ': {'PZ', 'NE', 'NC', 'VO'},
           'ʏ': {'LZ', 'PZ', 'NE', 'NC', 'VO'},
           'ʊ': {'LZ', 'VZ', 'NE', 'NC', 'VO'},
           'e': {'PA', 'MC', 'VO'},
           'ẽ': {'PA', 'MC', 'VO', 'NZ'},
           'ø': {'LZ', 'PA', 'MC', 'VO'},
           'ɘ': {'NE', 'MC', 'VO'},
           'ɵ': {'LZ', 'NE', 'MC', 'VO'},
           'ɤ': {'VE', 'MC', 'VO'},
           'o': {'LZ', 'VE', 'MC', 'VO'},
           'õ': {'LZ', 'VE', 'MC', 'VO', 'NZ'},
           'ə': {'NE', 'MI', 'VO'},
           'ɛ': {'PA', 'MO', 'VO'},
           'œ': {'LZ', 'PA', 'MO', 'VO'},
           'ɜ': {'NE', 'MO', 'VO'},
           'ɞ': {'LZ', 'NE', 'MO', 'VO'},
           'ʌ': {'VE', 'MO', 'VO'},
           'ɔ': {'LZ', 'VE', 'MO', 'VO'},
           'æ': {'PA', 'NO', 'VO'},
           'ɐ': {'NE', 'NO', 'VO'},
           'a': {'PA', 'OP', 'VO'},
           'ã': {'PA', 'OP', 'VO', 'NZ'},
           'ɶ': {'LZ', 'PA', 'OP', 'VO'},
           'ä': {'NE', 'OP', 'VO'},
           'ɑ': {'VE', 'OP', 'VO'},
           'ɒ': {'LZ', 'VE', 'OP', 'VO'},
           'ɚ': {'RZ', 'NE', 'MI', 'VO'},
           'ɝ': {'RZ', 'NE', 'MO', 'VO'}
           }

ignore_set = {'.', 'ˈ', 'ˌ', 'ː', 'ˑ', '*', '´', '′', '˘', '˧', '˩', '˨', '˦', '˥', 'ꜜ', '1',
              '2', '²', '³', '⁽', '⁾', '/', '(', ')', '⟨', '⟩', 'ˣ', '‿', ' ',
              u'\u0300', u'\u0301', u'\u0302', u'\u0304', u'\u030c', u'\u031a', u'\u0320',
              u'\u0324', u'\u0329', u'\u032f', u'\u0330', u'\u033a', u'\u033b', u'\u035C',
              u'\u0361', u'\u1dc4', u'\u1dc5', u'\u1dc8'}

modifiers = {'ᵝ': {'action': 'add', 'args': ['LZ']},
             '˞': {'action': 'add', 'args': ['RZ']},
             'ʲ': {'action': 'add', 'args': ['PZ']},
             'ˠ': {'action': 'add', 'args': ['VZ']},
             'ʷ': {'action': 'add', 'args': ['LZ', 'VZ']},
             'ˁ': {'action': 'add', 'args': ['HZ']},
             'ˀ': {'action': 'add', 'args': ['GZ']},
             'ˡ': {'action': 'add', 'args': ['LA']},
             'ʰ': {'action': 'add', 'args': ['AS']},
             'ʱ': {'action': 'add', 'args': ['AS', 'VO']},
             'ʼ': {'action': 'add', 'args': ['EJ']},
             u'\u0303': {'action': 'add', 'args': ['NZ']},
             u'\u030a': {'action': 'remove', 'args': ['VO']},
             u'\u0322': {'action': 'make', 'args': ['places', 'RE']},
             u'\u0325': {'action': 'remove', 'args': ['VO']},
             u'\u032c': {'action': 'add', 'args': ['VO']},
             u'\u031f': {'action': 'advance', 'args': []},
             u'\u031e': {'action': 'lower', 'args': []},
             u'\u031d': {'action': 'upper', 'args': []},
             u'\u032a': {'action': 'dentalize', 'args': []},
             u'\u0339': {'action': 'add_and_remove', 'args': [['LH'], ['LZ']]},
             u'\u02be': {'action': 'add_and_remove', 'args': [['LH'], ['LZ']]},
             u'\u0348': {'action': 'add', 'args': ['IT']}
            }

coronals = {'DE', 'AL', 'PO', 'RE'}
vowels = {'CL', 'NC', 'MC', 'MI', 'MO', 'NO', 'OP'}
places = {'LB', 'LD', 'LL', 'DE', 'AL', 'PO', 'RE', 'PA', 'NE', 'VE', 'UV', 'PH', 'GL'}
secondary_places = {'LZ', 'LH', 'RZ', 'PZ', 'VZ', 'HZ', 'GZ'}
manners = {'NA', 'PL', 'NF', 'SF', 'NS', 'SS', 'VI', 'TA', 'CL', 'NC', 'MC', 'MI', 'MO', 'NO', 'OP'}
secondary_manners = {'NZ', 'LA'}
airflows = {'AS', 'EJ', 'IT', 'IN', 'VO'}
features = {'places': places,
            'secondary_places': secondary_places,
            'manners': manners,
            'secondary_manners': secondary_manners,
            'airflows': airflows}

feature_names = {'LB': 'Labial', 'LD': 'Labiodental', 'LL': 'Labiolingual', 'DE': 'Dental',
                 'AL': 'Alveolar', 'PO': 'Postalveolar', 'RE': 'Retroflex', 'PA': 'Palatal',
                 'NE': 'Neutral', 'VE': 'Velar', 'UV': 'Uvular', 'PH': 'Pharyngeal', 'GL': 'Glottal',
                 'LZ': 'Labialized', 'LH': 'Half-labialized', 'RZ': 'Rhoticized', 'PZ': 'Palatalized',
                 'VZ': 'Velarized', 'HZ': 'Pharyngealized', 'GZ': 'Glottalize',
                 'NZ': 'Nasalized', 'NA': 'Nasal', 'PL': 'Plosive', 'NF': 'Nonsibilant affricate', 'SF': 'Sibilant affricate',
                 'NS': 'Nonsibilant fricative', 'SS': 'Sibilant fricative', 'VI': 'Vibrant', 'TA': 'Tap',
                 'SV': 'Approximant', 'CL': 'Closed', 'NC': 'Near-closed', 'MC': 'Mid-closed', 'MI': 'Mid',
                 'MO': 'Mid-open', 'NO': 'Near-open', 'OP': 'Opened', 'LA': 'Lateral',
                 'VO': 'Voiced', 'AS': 'Aspirated', 'EJ': 'Ejective', 'IT': 'Intensive', 'IN': 'Ingressive'}
