letters = {'p': {'LB': 12, 'PL': 12},
           'b': {'LB': 12, 'PL': 12, 'VO': 12},
           't': {'AL': 12, 'PL': 12},
           'ṭ': {'AL': 12, 'PL': 12, 'replace_with': 't'},
           'd': {'AL': 12, 'PL': 12, 'VO': 12},
           'ᵈ': {'AL': 12, 'PL': 12, 'VO': 12, 'replace_with': 'd'},
           'ʈ': {'RE': 12, 'PL': 12},
           'ɖ': {'RE': 12, 'PL': 12, 'VO': 12},
           'c': {'PA': 12, 'PL': 12},
           'ɟ': {'PA': 12, 'PL': 12, 'VO': 12},
           'k': {'VE': 12, 'PL': 12},
           'g': {'VE': 12, 'PL': 12, 'VO': 12},
           'ɡ': {'VE': 12, 'PL': 12, 'VO': 12, 'replace_with': 'g'},
           'ᶢ': {'VE': 12, 'PL': 12, 'VO': 12, 'replace_with': 'g'},
           'q': {'UV': 12, 'PL': 12},
           'ɢ': {'UV': 12, 'PL': 12, 'VO': 12},
           'ʡ': {'PH': 12, 'PL': 12},
           'ʔ': {'GL': 12, 'PL': 12},

           'm': {'LB': 12, 'NA': 12, 'VO': 12},
           'ḿ': {'LB': 12, 'NA': 12, 'VO': 12, 'replace_with': 'm'},
           'ᵐ': {'LB': 12, 'NA': 12, 'VO': 12, 'replace_with': 'm'},
           'ɱ': {'LD': 12, 'NA': 12, 'VO': 12},
           'ᶬ': {'LD': 12, 'NA': 12, 'VO': 12, 'replace_with': 'ɱ'},
           'n': {'AL': 12, 'NA': 12, 'VO': 12},
           'ṅ': {'AL': 12, 'NA': 12, 'VO': 12, 'replace_with': 'n'},
           'ṇ': {'AL': 12, 'NA': 12, 'VO': 12, 'replace_with': 'n'},
           'ǹ': {'AL': 12, 'NA': 12, 'VO': 12, 'replace_with': 'n'},
           'ⁿ': {'AL': 12, 'NA': 12, 'VO': 12, 'replace_with': 'n'},
           'ɳ': {'RE': 12, 'NA': 12, 'VO': 12},
           'ɲ': {'PA': 12, 'NA': 12, 'VO': 12},
           'ñ': {'PA': 12, 'NA': 12, 'VO': 12, 'replace_with': 'ɲ'},
           'ŋ': {'VE': 12, 'NA': 12, 'VO': 12},
           'ᵑ': {'VE': 12, 'NA': 12, 'VO': 12, 'replace_with': 'ŋ'},
           'ɴ': {'UV': 12, 'NA': 12, 'VO': 12},

           'ʙ': {'LB': 12, 'VI': 12, 'VO': 12},
           'r': {'AL': 12, 'VI': 12, 'VO': 12},
           'ŕ': {'AL': 12, 'VI': 12, 'VO': 12, 'replace_with': 'r'},
           'ṛ': {'AL': 12, 'VI': 12, 'VO': 12, 'replace_with': 'r'},
           'ʀ': {'UV': 12, 'VI': 12, 'VO': 12},
           'ʜ': {'PH': 12, 'VI': 12},
           'ʢ': {'PH': 12, 'VI': 12, 'VO': 12},

           'ⱱ': {'LD': 12, 'TA': 12, 'VO': 12},
           'ɾ': {'AL': 12, 'TA': 12, 'VO': 12},
           'ɽ': {'RE': 12, 'TA': 12, 'VO': 12},

           'ɸ': {'LB': 12, 'SP': 12},
           'β': {'LB': 12, 'SP': 12, 'VO': 12},
           'f': {'LD': 12, 'SP': 12},
           'v': {'LD': 12, 'SP': 12, 'VO': 12},
           'θ': {'DE': 12, 'SP': 12},
           'ð': {'DE': 12, 'SP': 12, 'VO': 12},
           's': {'AL': 12, 'SP': 12},
           'z': {'AL': 12, 'SP': 12, 'VO': 12},
           'ʃ': {'PO': 12, 'SP': 12},
           'ʒ': {'PO': 12, 'SP': 12, 'VO': 12},
           'ʂ': {'RE': 12, 'SP': 12},
           'ʐ': {'RE': 12, 'SP': 12, 'VO': 12},
           'ç': {'PA': 12, 'SP': 12},
           'ʝ': {'PA': 12, 'SP': 12, 'VO': 12},
           'x': {'VE': 12, 'SP': 12},
           'ɣ': {'VE': 12, 'SP': 12, 'VO': 12},
           'χ': {'UV': 12, 'SP': 12},
           'ʁ': {'UV': 12, 'SP': 12, 'VO': 12},
           'ħ': {'PH': 12, 'SP': 12},
           'ʕ': {'PH': 12, 'SP': 9, 'CL': 3, 'VO': 12},
           'h': {'GL': 12, 'SP': 9, 'CL': 3},
           'ḥ': {'GL': 12, 'SP': 9, 'CL': 3, 'replace_with': 'h'},
           'ɦ': {'GL': 12, 'SP': 9, 'CL': 3, 'VO': 12},
           'ɬ': {'AL': 12, 'SP': 12, 'LA': 12},
           'ɮ': {'AL': 12, 'SP': 12, 'LA': 12, 'VO': 12},

           'ʋ': {'LD': 12, 'SP': 6, 'CL': 6, 'VO': 12},
           'ɹ': {'AL': 12, 'SP': 6, 'CL': 6, 'VO': 12},
           'ɻ': {'RE': 12, 'SP': 6, 'CL': 6, 'VO': 12},
           'j': {'PA': 12, 'SP': 6, 'CL': 6, 'VO': 12},
           'ɰ': {'VE': 12, 'SP': 6, 'CL': 6, 'VO': 12},

           'l': {'AL': 12, 'SP': 6, 'CL': 6, 'LA': 12, 'VO': 12},
           'ĺ': {'AL': 12, 'SP': 6, 'CL': 6, 'LA': 12, 'VO': 12, 'replace_with': 'l'},
           'ḹ': {'AL': 12, 'SP': 6, 'CL': 6, 'LA': 12, 'VO': 12, 'replace_with': 'l'},
           'ɭ': {'RE': 12, 'SP': 6, 'CL': 6, 'LA': 12, 'VO': 12},
           'ʎ': {'PA': 12, 'SP': 6, 'CL': 6, 'LA': 12, 'VO': 12},
           'ʟ': {'VE': 12, 'SP': 6, 'CL': 6, 'LA': 12, 'VO': 12},

           'ʘ': {'LB': 12, 'PL': 12, 'EJ': 6, 'IN': 6},
           'ǀ': {'DE': 12, 'PL': 12, 'EJ': 6, 'IN': 6},
           'ǃ': {'AL': 12, 'PL': 12, 'EJ': 6, 'IN': 6},
           '‼': {'RE': 12, 'PL': 12, 'EJ': 6, 'IN': 6},
           'ǂ': {'PA': 12, 'PL': 12, 'EJ': 6, 'IN': 6},
           'ʞ': {'VE': 12, 'PL': 12, 'EJ': 6, 'IN': 6},
           'ǁ': {'PL': 12, 'LA': 12, 'EJ': 6, 'IN': 6},

           'ɓ': {'LB': 12, 'PL': 12, 'VO': 12, 'IN': 12},
           'ɗ': {'AL': 12, 'PL': 12, 'VO': 12, 'IN': 12},
           'ᶑ': {'RE': 12, 'PL': 12, 'VO': 12, 'IN': 12},
           'ʄ': {'PA': 12, 'PL': 12, 'VO': 12, 'IN': 12},
           'ɠ': {'VE': 12, 'PL': 12, 'VO': 12, 'IN': 12},
           'ʛ': {'UV': 12, 'PL': 12, 'VO': 12, 'IN': 12},

           'ʍ': {'LB': 6, 'VE': 6, 'SP': 6, 'CL': 6, 'VO': 12},
           'w': {'LB': 6, 'VE': 6, 'SP': 6, 'CL': 6, 'VO': 12},
           'ɥ': {'LB': 6, 'PA': 6, 'SP': 6, 'CL': 6, 'VO': 12},
           'ɫ': {'AL': 6, 'VE': 6, 'SP': 6, 'CL': 6, 'LA': 12, 'VO': 12},
           'ɺ': {'AL': 12, 'TA': 12, 'LA': 12, 'VO': 12},
           'ɕ': {'AL': 6, 'PA': 6, 'SP': 12},
           'ʑ': {'AL': 6, 'PA': 6, 'SP': 12, 'VO': 12},
           'ȵ': {'AL': 6, 'PA': 6, 'VO': 12, 'NA': 12},
           'ɧ': {'PO': 6, 'VE': 6, 'SP': 12},

           'i': {'PA': 12, 'CL': 12, 'VO': 12},
           'ĩ': {'PA': 12, 'CL': 12, 'VO': 12, 'NA': 12},
           'ī': {'PA': 12, 'CL': 12, 'VO': 12, 'replace_with': 'i'},
           'î': {'PA': 12, 'CL': 12, 'VO': 12, 'replace_with': 'i'},
           'í': {'PA': 12, 'CL': 12, 'VO': 12, 'replace_with': 'i'},
           'ì': {'PA': 12, 'CL': 12, 'VO': 12, 'replace_with': 'i'},
           'ḭ': {'PA': 12, 'CL': 12, 'VO': 12, 'replace_with': 'i'},
           'ǐ': {'PA': 12, 'CL': 12, 'VO': 12, 'replace_with': 'i'},
           'y': {'LB': 6, 'PA': 6, 'CL': 12, 'VO': 12},
           'ỹ': {'LB': 6, 'PA': 6, 'CL': 12, 'VO': 12, 'NA': 12},
           'ý': {'LB': 6, 'PA': 6, 'CL': 12, 'VO': 12, 'replace_with': 'y'},
           'ẏ': {'LB': 6, 'PA': 6, 'CL': 12, 'VO': 12, 'replace_with': 'y'},
           'ɨ': {'PA': 6, 'VE': 6, 'CL': 12, 'VO': 12},
           'ʉ': {'LB': 6, 'PA': 3, 'VE': 3, 'CL': 12, 'VO': 12},
           'ɯ': {'VE': 12, 'CL': 12, 'VO': 12},
           'u': {'LB': 6, 'VE': 6, 'CL': 12, 'VO': 12},
           'ũ': {'LB': 6, 'VE': 6, 'CL': 12, 'VO': 12, 'NA': 12},
           'ù': {'LB': 6, 'VE': 6, 'CL': 12, 'VO': 12, 'replace_with': 'u'},
           'ū': {'LB': 6, 'VE': 6, 'CL': 12, 'VO': 12, 'replace_with': 'u'},
           'ú': {'LB': 6, 'VE': 6, 'CL': 12, 'VO': 12, 'replace_with': 'u'},
           'û': {'LB': 6, 'VE': 6, 'CL': 12, 'VO': 12, 'replace_with': 'u'},
           'ǔ': {'LB': 6, 'VE': 6, 'CL': 12, 'VO': 12, 'replace_with': 'u'},
           'ṵ': {'LB': 6, 'VE': 6, 'CL': 12, 'VO': 12, 'replace_with': 'u'},
           'ṳ': {'LB': 6, 'VE': 6, 'CL': 12, 'VO': 12, 'replace_with': 'u'},
           'ɪ': {'PA': 8, 'VE': 4, 'CL': 10, 'OP': 2, 'VO': 12},
           'ʏ': {'LB': 6, 'PA': 4, 'VE': 2, 'CL': 10, 'OP': 2, 'VO': 12},
           'ʊ': {'LB': 6, 'PA': 2, 'VE': 4, 'CL': 10, 'OP': 2, 'VO': 12},
           'e': {'PA': 12, 'CL': 8, 'OP': 4, 'VO': 12},
           'ẽ': {'PA': 12, 'CL': 8, 'OP': 4, 'VO': 12, 'NA': 12},
           'é': {'PA': 12, 'CL': 8, 'OP': 4, 'VO': 12, 'replace_with': 'e'},
           'è': {'PA': 12, 'CL': 8, 'OP': 4, 'VO': 12, 'replace_with': 'e'},
           'ê': {'PA': 12, 'CL': 8, 'OP': 4, 'VO': 12, 'replace_with': 'e'},
           'ĕ': {'PA': 12, 'CL': 8, 'OP': 4, 'VO': 12, 'replace_with': 'e'},
           'ě': {'PA': 12, 'CL': 8, 'OP': 4, 'VO': 12, 'replace_with': 'e'},
           'ḛ': {'PA': 12, 'CL': 8, 'OP': 4, 'VO': 12, 'replace_with': 'e'},
           'ø': {'LB': 6, 'PA': 6, 'CL': 8, 'OP': 4, 'VO': 12},
           'ɘ': {'PA': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO': 12},
           'ɵ': {'LB': 6, 'PA': 3, 'VE': 3, 'CL': 8, 'OP': 4, 'VO': 12},
           'ɤ': {'VE': 12, 'CL': 8, 'OP': 4, 'VO': 12},
           'o': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO': 12},
           'õ': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO': 12, 'NA': 12},
           'ó': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO': 12, 'replace_with': 'o'},
           'ò': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO': 12, 'replace_with': 'o'},
           'ô': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO': 12, 'replace_with': 'o'},
           'ō': {'LB': 6, 'VE': 6, 'CL': 8, 'OP': 4, 'VO': 12, 'replace_with': 'o'},
           'ə': {'PA': 6, 'VE': 6, 'CL': 6, 'OP': 6, 'VO': 12},
           'ɛ': {'PA': 12, 'CL': 4, 'OP': 8, 'VO': 12},
           'œ': {'LB': 6, 'PA': 6, 'CL': 4, 'OP': 8, 'VO': 12},
           'ɜ': {'PA': 6, 'VE': 6, 'CL': 4, 'OP': 8, 'VO': 12},
           'ɞ': {'LB': 6, 'PA': 3, 'VE': 3, 'CL': 4, 'OP': 8, 'VO': 12},
           'ʌ': {'VE': 12, 'CL': 4, 'OP': 8, 'VO': 12},
           'ɔ': {'LB': 6, 'VE': 6, 'CL': 4, 'OP': 8, 'VO': 12},
           'æ': {'PA': 12, 'CL': 2, 'OP': 10, 'VO': 12},
           'ǣ': {'PA': 12, 'CL': 2, 'OP': 10, 'VO': 12, 'replace_with': 'æ'},
           'ɐ': {'PA': 6, 'VE': 6, 'CL': 2, 'OP': 10, 'VO': 12},
           'a': {'PA': 12, 'OP': 12, 'VO': 12},
           'ã': {'PA': 12, 'OP': 12, 'VO': 12, 'NA': 12},
           'á': {'PA': 12, 'OP': 12, 'VO': 12, 'replace_with': 'a'},
           'â': {'PA': 12, 'OP': 12, 'VO': 12, 'replace_with': 'a'},
           'ā': {'PA': 12, 'OP': 12, 'VO': 12, 'replace_with': 'a'},
           'à': {'PA': 12, 'OP': 12, 'VO': 12, 'replace_with': 'a'},
           'ǎ': {'PA': 12, 'OP': 12, 'VO': 12, 'replace_with': 'a'},
           'ạ': {'PA': 12, 'OP': 12, 'VO': 12, 'replace_with': 'a'},
           'ɶ': {'LB': 6, 'PA': 6, 'OP': 12, 'VO': 12},
           'ä': {'PA': 6, 'VE': 6, 'OP': 12, 'VO': 12},
           'ɑ': {'VE': 12, 'OP': 12, 'VO': 12},
           'ɒ': {'LB': 6, 'VE': 6, 'OP': 12, 'VO': 12},
           'ɚ': {'AL': 6, 'PA': 3, 'VE': 3, 'CL': 6, 'OP': 6, 'VO': 12},
           'ɝ': {'AL': 6, 'PA': 3, 'VE': 3, 'CL': 4, 'OP': 8, 'VO': 12}
           }

ignore_set = {'.', 'ˈ', 'ˌ', 'ː', 'ˑ', '*', '´', '′', '˘', '˧', '˩', '˨', '˦', '˥', 'ꜜ', '1',
              '2', '²', '³', '⁽', '⁾', '/', '(', ')', '⟨', '⟩', 'ˣ', '‿', ' ',
              u'\u0300', u'\u0301', u'\u0302', u'\u0304', u'\u030c', u'\u031a', u'\u0320',
              u'\u0324', u'\u0329', u'\u032f', u'\u0330', u'\u033a', u'\u033b', u'\u035C',
              u'\u0361', u'\u1dc4', u'\u1dc5', u'\u1dc8'}

modifiers = {'ᵝ': {'action': 'add', 'args': ['LB']},
             '˞': {'action': 'add', 'args': ['AL']},
             'ʴ': {'action': 'add', 'args': ['AL'], 'replace_with': '˞'},
             'ʲ': {'action': 'add', 'args': ['PA']},
             'ˠ': {'action': 'add', 'args': ['VE']},
             'ʷ': {'action': 'add', 'args': ['LB', 'VE']},
             'ˁ': {'action': 'add', 'args': ['PH']},
             'ˀ': {'action': 'add', 'args': ['GL']},
             'ˡ': {'action': 'add', 'args': ['LA']},
             'ʰ': {'action': 'add', 'args': ['AS']},
             'ʱ': {'action': 'add', 'args': ['AS', 'VO']},
             'ʼ': {'action': 'add', 'args': ['EJ']},
             u'\u0303': {'action': 'add', 'args': ['NA']},
             u'\u030a': {'action': 'devoice', 'args': []},
             u'\u0322': {'action': 'make', 'args': ['places', 'RE']},
             u'\u0325': {'action': 'devoice', 'args': []},
             u'\u032c': {'action': 'add', 'args': ['VO']},
             u'\u031f': {'action': 'advance', 'args': []},
             u'\u031e': {'action': 'lower', 'args': []},
             u'\u031d': {'action': 'upper', 'args': []},
             u'\u032a': {'action': 'dentalize', 'args': []},
             u'\u0339': {'action': 'half_labialize', 'args': []},
             u'\u02be': {'action': 'half_labialize', 'args': []},
             u'\u0348': {'action': 'intensify', 'args': []},
             'ṃ': {'action': 'add', 'args': ['NA'], 'replace_with': u'\u0303'}
             }

coronals = {'DE', 'AL', 'PO', 'RE'}
places = {'LB', 'LD', 'LL', 'DE', 'AL', 'PO', 'RE', 'PA', 'VE', 'UV', 'PH', 'GL'}
manners = {'PL', 'SP', 'VI', 'TA', 'CL', 'OP'}
nasalization = {'NA'}
lateralization = {'LA'}
voiceness = {'VO'}
airflows = {'AS', 'EJ', 'IN'}
features = {'places': places,
            'manners': manners,
            'nasalization': nasalization,
            'lateralization': lateralization,
            'voiceness': voiceness,
            'airflows': airflows}

feature_names = {'LB': 'Labial', 'LD': 'Labiodental', 'LL': 'Labiolingual', 'DE': 'Dental',
                 'AL': 'Alveolar', 'PO': 'Postalveolar', 'RE': 'Retroflex', 'PA': 'Palatal',
                 'VE': 'Velar', 'UV': 'Uvular', 'PH': 'Phalingeal', 'GL': 'Glotal',
                 'PL': 'Plosive', 'SP': 'Fricative', 'VI': 'Vibrant', 'TA': 'Tap',
                 'CL': 'Closed', 'OP': 'Opened', 'NA': 'Nasal', 'LA': 'Lateral',
                 'VO': 'Voiced', 'AS': 'Aspirated', 'EJ': 'Ejective', 'IN': 'Ingressive'}
